version: "3.5"
services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 shortify.app
    ports:
      - target: 5000
        published: 5000
    volumes:
      - type: volume
        source: shortify-vol
        target: /app
    depends_on:
      - redis
  redis:
    image: "redis:alpine"

volumes:
  shortify-vol:
